<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Credits</name>
   <tag></tag>
   <elementGuidId>b7fdcac0-1f77-4f65-80b6-0b2aaed8d6f3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credits</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;content box&quot;]/form[1]/fieldset[@class=&quot;uk-fieldset&quot;]/div[@class=&quot;uk-overflow-auto&quot;]/table[1]/thead[1]/tr[1]/th[2]</value>
   </webElementProperties>
</WebElementEntity>
