<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_001</name>
   <tag></tag>
   <elementGuidId>4bca6d47-7d5b-471e-a163-15966bf7eccd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uk-text-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;content box&quot;]/ul[@class=&quot;uk-accordion&quot;]/li[@class=&quot;uk-open&quot;]/div[@class=&quot;uk-accordion-content&quot;]/div[@class=&quot;uk-overflow-auto&quot;]/table[@class=&quot;uk-table uk-table-justify uk-table-divider uk-table-striped&quot;]/tbody[1]/tr[1]/td[@class=&quot;uk-text-center&quot;]</value>
   </webElementProperties>
</WebElementEntity>
