<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_GPA</name>
   <tag></tag>
   <elementGuidId>45739651-37c7-46e4-9357-3c254b214ff4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GPA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;content box&quot;]/div[@class=&quot;uk-width-4-6@m uk-width-2-3@s&quot;]/div[@class=&quot;uk-overflow-auto&quot;]/table[@class=&quot;uk-table uk-table-divider&quot;]/tbody[1]/tr[4]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
