<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Withdraw</name>
   <tag></tag>
   <elementGuidId>866ff3ba-9cc5-460b-9086-a847741211a9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uk-button uk-button-danger</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#modal-sections</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;content box&quot;]/ul[@class=&quot;uk-accordion&quot;]/li[@class=&quot;uk-open&quot;]/div[@class=&quot;uk-accordion-content&quot;]/div[@class=&quot;uk-overflow-auto&quot;]/table[@class=&quot;uk-table uk-table-justify uk-table-divider uk-table-striped&quot;]/tbody[1]/tr[1]/td[@class=&quot;uk-text-center&quot;]/a[@class=&quot;uk-button uk-button-danger&quot;]</value>
   </webElementProperties>
</WebElementEntity>
