<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>f6477a51-c3a7-4330-817e-32b5110f8bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;uk-modal-page&quot;]/body[1]/div[@id=&quot;modal-sections&quot;]/div[@class=&quot;uk-modal-dialog&quot;]/div[@class=&quot;uk-modal-footer uk-text-right&quot;]/button[@class=&quot;uk-button uk-button-default uk-modal-close&quot;][count(. | //button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')]) = count(//button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uk-button uk-button-default uk-modal-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;uk-modal-page&quot;]/body[1]/div[@id=&quot;modal-sections&quot;]/div[@class=&quot;uk-modal-dialog&quot;]/div[@class=&quot;uk-modal-footer uk-text-right&quot;]/button[@class=&quot;uk-button uk-button-default uk-modal-close&quot;]</value>
   </webElementProperties>
</WebElementEntity>
