<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_None</name>
   <tag></tag>
   <elementGuidId>adc12a83-6e8c-4c2d-8c1a-ea8c8f5a2c85</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uk-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UIkit.notification({message: 'Set the grade success.', status: 'success', timeout:500})</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            None
                                                            A
                                                            B+
                                                            B
                                                            C+
                                                            C
                                                            D+
                                                            D
                                                            F
                                                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;uk-container&quot;]/div[@class=&quot;content box&quot;]/div[@class=&quot;uk-overflow-auto&quot;]/table[@class=&quot;uk-table uk-table-justify uk-table-divider uk-table-striped&quot;]/tbody[1]/tr[1]/td[@class=&quot;uk-text-center&quot;]/form[1]/div[@class=&quot;uk-margin&quot;]/div[1]/select[@class=&quot;uk-select&quot;]</value>
   </webElementProperties>
</WebElementEntity>
